spring:
  profiles: default
  main:
    web-environment: false
apiToken: ${API_TOKEN}
projectAPIUrl: ${PROJECT_API_URL}
prodEnvironmentName: ${PROD_ENVIRONMENT_NAME:prod}
deploymentWindowInDays: ${DEPLOYMENT_WINDOW_IN_DAYS:90}
shiftLeftInDays: ${SHIFT_LEFT_IN_DAYS:154}